name: Test Project

on: [pull_request]

jobs:
  test:
    name: Test Surrounded
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
      # Test
      - name: Test project
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: surrounded/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      # Upload Artifact
      - name: upload
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results
          path: artifacts


